package com.example.ui.theme

object Localization {
    private val translations = mapOf(
        "TR" to mapOf(
            "app_title" to "AL HUKUK AI OS",
            "welcome" to "AL Hukuk Yapay Zeka Sistemine Hoş Geldiniz",
            "tagline" to "Hukuk Ofisi, Dava Simülatörü, Araştırma Motoru ve Dilekçe Stüdyosu tek bir güçlü platformda.",
            "search_placeholder" to "Sorunuzu yazın... (Örn: İş Kanunu fazla mesai)",
            "run_search" to "Hukuk Motorunda Ara",
            "create_file" to "Yeni Dosya Oluştur",
            "active_files" to "Aktif Dosyalar (Maks 10)",
            "file_title" to "Dosya / Dava Başlığı",
            "client_name" to "Müvekkil Adı",
            "case_description" to "Uyuşmazlık Konusu ve Olay Özeti",
            "description_hint" to "Olayı detaylıca anlatın, zaman çizelgesi ve iddialar çıkarılacaktır.",
            "save" to "Kaydet",
            "cancel" to "İptal",
            "status_active" to "Aktif",
            "status_closed" to "Kapatıldı",
            "status_pending" to "Beklemede",
            "workspace" to "Dosya Çalışma Alanı",
            "tab_chat" to "Hukuk Beyni",
            "tab_simulator" to "Dava Simülatörü",
            "tab_documents" to "Dosya Merkezi",
            "tab_calendar" to "Takvim & Not",
            "tab_academy" to "Hukuk Akademisi",
            "tab_petition" to "Dilekçe Stüdyosu",
            "simulator_run" to "Yapay Zeka Simülasyonunu Çalıştır",
            "simulator_intro" to "Olay detaylarını analiz ederek kronoloji, iddialar, eksik noktalar ve risk senaryoları çıkarın.",
            "simulator_timeline" to "⏰ Olay Zaman Çizelgesi",
            "simulator_claims" to "⚖️ İddialar ve Deliller",
            "simulator_missing" to "🔍 Eksik Noktalar & Tespitler",
            "simulator_scenarios" to "🔮 Hukuki Senaryolar & İhtimaller",
            "simulator_strengths" to "💪 Güçlü & Zayıf Yönler",
            "docs_upload" to "Yeni Belge Yükle / Tara",
            "docs_name" to "Belge Adı",
            "docs_type" to "Belge Tipi",
            "docs_content" to "Belge Metni veya Kısa Özeti",
            "docs_unreadable" to "⚠️ Okunamayan veya Eksik Kısım Var!",
            "docs_summary" to "📄 Belge Analiz Özeti",
            "docs_dates" to "📅 Önemli Tarihler",
            "docs_persons" to "👥 Adı Geçen Kişiler / Kurumlar",
            "calendar_add" to "Etkinlik/Tarih Ekle",
            "calendar_title" to "Etkinlik Başlığı",
            "calendar_type" to "Tür",
            "calendar_date" to "Tarih (YYYY-AA-GG)",
            "calendar_desc" to "Açıklama",
            "type_hearing" to "Duruşma",
            "type_deadline" to "İtiraz Süresi",
            "type_notification" to "Tebligat",
            "type_other" to "Diğer",
            "notes_title" to "Dosya Özel Notları (Otomatik Kaydedilir)",
            "academy_title" to "Hukuk Akademisi",
            "academy_intro" to "Hukuk bilginizi test edin, quizleri tamamlayın ve Başarı Sertifikası kazanın!",
            "academy_start" to "Akademi Sınavını Başlat",
            "academy_score" to "Mevcut Akademi Puanı",
            "academy_cert" to "🏆 Hukuk Başarı Sertifikası",
            "academy_cert_desc" to "AL Hukuk AI OS Akademisi sınavlarında üstün başarı göstererek hukuki yeterlilik sertifikasını almaya hak kazanmıştır.",
            "premium_title" to "Premium Üyelik",
            "premium_desc" to "Sınırsız dilekçe indirme, dosya tahlili ve kesintisiz sesli avukat desteği için Premium'a geçin.",
            "premium_upgrade" to "Premium'a Yükselt",
            "premium_status" to "Üyelik Durumu",
            "premium_active" to "Premium Üye",
            "premium_free" to "Standart Üye",
            "premium_iban" to "Ödeme IBAN Hesabı (Havale/EFT)",
            "premium_receipt" to "Dekont Yükle & Onayla",
            "voice_assistant" to "Sesli Avukat AI",
            "voice_speak" to "Konuşmak için basılı tutun...",
            "camera_scanner" to "Belge Kamerası (OCR)",
            "camera_capture" to "Belgeyi Tara & Özetle",
            "camera_mock_text" to "Kira Sözleşmesi Taslağı - Kiraya veren: Ahmet Y., Kiracı: Mehmet K. Kira başlangıcı: 01.01.2026. Kira bedeli: 15.000 TL.",
            "language" to "Dil / Language / Sprache / لغة",
            "settings" to "Ayarlar",
            "missing_points_title" to "🤖 AI Eksik Noktalar Analizi",
            "missing_points_intro" to "Davanın daha güçlü savunulabilmesi için yapay zeka tarafından tespit edilen eksikler:",
            "petition_form_title" to "Dilekçe Hazırlama Formu",
            "petition_court" to "Yetkili Mahkeme (Örn: İstanbul Anadolu 4. İş Mahkemesi)",
            "petition_plaintiff" to "Davacı Bilgileri (Ad Soyad, TC, Adres)",
            "petition_defendant" to "Davalı Bilgileri (Ad Soyad, Unvan, Adres)",
            "petition_subject" to "Dava Konusu (Örn: Kıdem ve ihbar tazminatı talebi)",
            "petition_facts" to "Olayların Gelişimi (Açıklamalar)",
            "petition_generate" to "Dilekçe Taslağı Oluştur",
            "petition_export" to "Word / PDF Olarak İndir (Simüle)",
            "active_tab_ofis" to "Hukuk Ofisi",
            "active_tab_simulator" to "Dava Simülatörü",
            "active_tab_search" to "AI Danışman",
            "active_tab_petition" to "Dilekçe Stüdyosu",
            "active_tab_academy" to "Akademi",
            "active_tab_voice" to "Sesli Avukat",
            "active_tab_camera" to "Kamera OCR",
            "active_tab_settings" to "Profil & Ayarlar"
        ),
        "EN" to mapOf(
            "app_title" to "AL LAW AI OS",
            "welcome" to "Welcome to AL Law Artificial Intelligence System",
            "tagline" to "Law Office, Case Simulator, Research Engine, and Petition Studio in one powerful platform.",
            "search_placeholder" to "Write your question... (e.g. Labor Law overtime pay)",
            "run_search" to "Search Law Engine",
            "create_file" to "Create New Case File",
            "active_files" to "Active Case Files (Max 10)",
            "file_title" to "Case / File Title",
            "client_name" to "Client Name",
            "case_description" to "Subject of Dispute and Case Summary",
            "description_hint" to "Describe the case in detail; timeline, claims, and evidence suggestions will be generated.",
            "save" to "Save",
            "cancel" to "Cancel",
            "status_active" to "Active",
            "status_closed" to "Closed",
            "status_pending" to "Pending",
            "workspace" to "Case File Workspace",
            "tab_chat" to "Legal Brain",
            "tab_simulator" to "Case Simulator",
            "tab_documents" to "Document Center",
            "tab_calendar" to "Calendar & Notes",
            "tab_academy" to "Law Academy",
            "tab_petition" to "Petition Studio",
            "simulator_run" to "Run AI Case Simulation",
            "simulator_intro" to "Analyze event details to extract chronology, claims, missing points, and scenario risks.",
            "simulator_timeline" to "⏰ Chronological Timeline",
            "simulator_claims" to "⚖️ Claims & Evidence",
            "simulator_missing" to "🔍 Missing Points & Deficiencies",
            "simulator_scenarios" to "🔮 Legal Scenarios & Outcomes",
            "simulator_strengths" to "💪 Strengths & Weaknesses",
            "docs_upload" to "Upload / Scan Document",
            "docs_name" to "Document Name",
            "docs_type" to "Document Type",
            "docs_content" to "Document Text or Summary",
            "docs_unreadable" to "⚠️ Unreadable or Missing Parts Detected!",
            "docs_summary" to "📄 Document Analysis Summary",
            "docs_dates" to "📅 Key Dates",
            "docs_persons" to "👥 Mentioned Parties",
            "calendar_add" to "Add Event/Deadline",
            "calendar_title" to "Event Title",
            "calendar_type" to "Type",
            "calendar_date" to "Date (YYYY-MM-DD)",
            "calendar_desc" to "Description",
            "type_hearing" to "Hearing",
            "type_deadline" to "Appeal/Objection Deadline",
            "type_notification" to "Notification",
            "type_other" to "Other",
            "notes_title" to "Private Notes (Auto-saved)",
            "academy_title" to "Law Academy",
            "academy_intro" to "Test your legal knowledge, complete quizzes, and earn an Academy Certificate!",
            "academy_start" to "Start Academy Quiz",
            "academy_score" to "Current Academy Score",
            "academy_cert" to "🏆 Certificate of Legal Excellence",
            "academy_cert_desc" to "Having demonstrated outstanding success in the examinations of AL Law AI OS Academy, is hereby awarded this certificate of legal proficiency.",
            "premium_title" to "Premium Subscription",
            "premium_desc" to "Upgrade to Premium for unlimited petition downloads, complete document analysis, and continuous Voice AI support.",
            "premium_upgrade" to "Upgrade to Premium",
            "premium_status" to "Membership Status",
            "premium_active" to "Premium Member",
            "premium_free" to "Standard Member",
            "premium_iban" to "Payment IBAN (Wire Transfer)",
            "premium_receipt" to "Upload Receipt & Confirm",
            "voice_assistant" to "Voice Lawyer AI",
            "voice_speak" to "Hold to speak...",
            "camera_scanner" to "Document Camera (OCR)",
            "camera_capture" to "Scan & Summarize Document",
            "camera_mock_text" to "Lease Agreement Draft - Landlord: Ahmet Y., Tenant: Mehmet K. Start date: 01.01.2026. Rent amount: 15,000 TRY.",
            "language" to "Language / Dil",
            "settings" to "Settings",
            "missing_points_title" to "🤖 AI Gap Analysis",
            "missing_points_intro" to "Deficiencies detected by AI for a stronger legal defense:",
            "petition_form_title" to "Petition Draft Form",
            "petition_court" to "Competent Court (e.g. Istanbul Anadolu 4th Labor Court)",
            "petition_plaintiff" to "Plaintiff Info (Full Name, ID, Address)",
            "petition_defendant" to "Defendant Info (Full Name, Title, Address)",
            "petition_subject" to "Subject of Claim (e.g. Claim for severance and notice pay)",
            "petition_facts" to "Facts of the Case (Explanations)",
            "petition_generate" to "Generate Petition Draft",
            "petition_export" to "Download Word / PDF (Simulated)",
            "active_tab_ofis" to "Law Office",
            "active_tab_simulator" to "Case Simulator",
            "active_tab_search" to "Research",
            "active_tab_petition" to "Petition Studio",
            "active_tab_academy" to "Academy",
            "active_tab_voice" to "Voice Lawyer",
            "active_tab_camera" to "Camera OCR",
            "active_tab_settings" to "Profile & Settings"
        ),
        "DE" to mapOf(
            "app_title" to "AL JURA AI OS",
            "welcome" to "Willkommen beim AL Jura KI-System",
            "tagline" to "Anwaltskanzlei, Fall-Simulator, Recherche-Engine und Schriftsatz-Studio in einer einzigen starken Plattform.",
            "search_placeholder" to "Geben Sie Ihre Frage ein... (z.B. Arbeitsrecht Überstunden)",
            "run_search" to "Recherche starten",
            "create_file" to "Neue Akte anlegen",
            "active_files" to "Aktive Akten (Max 10)",
            "file_title" to "Aktentitel / Betreff",
            "client_name" to "Mandantenname",
            "case_description" to "Gegenstand des Streits & Sachverhalt",
            "description_hint" to "Beschreiben Sie den Sachverhalt im Detail; Chronologie, Ansprüche und Beweisvorschläge werden generiert.",
            "save" to "Speichern",
            "cancel" to "Abbrechen",
            "status_active" to "Aktiv",
            "status_closed" to "Geschlossen",
            "status_pending" to "Wartend",
            "workspace" to "Akte-Arbeitsplatz",
            "tab_chat" to "Rechtshirn",
            "tab_simulator" to "Fall-Simulator",
            "tab_documents" to "Dokumentenzentrum",
            "tab_calendar" to "Fristen & Notiz",
            "tab_academy" to "Jura-Akademie",
            "tab_petition" to "Schriftsatz-Studio",
            "simulator_run" to "KI-Fallsimulation starten",
            "simulator_intro" to "Analysieren Sie den Sachverhalt, um Chronologie, Ansprüche, Lücken und Risiko-Szenarien zu ermitteln.",
            "simulator_timeline" to "⏰ Chronologische Zeitleiste",
            "simulator_claims" to "⚖️ Ansprüche & Beweise",
            "simulator_missing" to "🔍 Lücken & Mängel",
            "simulator_scenarios" to "🔮 Rechtliche Szenarien & Risiken",
            "simulator_strengths" to "💪 Stärken & Schwächen",
            "docs_upload" to "Dokument hochladen / Scannen",
            "docs_name" to "Dokumentname",
            "docs_type" to "Dokumenttyp",
            "docs_content" to "Inhalt oder Zusammenfassung",
            "docs_unreadable" to "⚠️ Unleserliche oder fehlende Teile erkannt!",
            "docs_summary" to "📄 Dokumentenanalyse-Zusammenfassung",
            "docs_dates" to "📅 Wichtige Termine",
            "docs_persons" to "👥 Beteiligte Parteien",
            "calendar_add" to "Frist/Ereignis hinzufügen",
            "calendar_title" to "Ereignis-Titel",
            "calendar_type" to "Typ",
            "calendar_date" to "Datum (JJJJ-MM-TT)",
            "calendar_desc" to "Beschreibung",
            "type_hearing" to "Gerichtstermin",
            "type_deadline" to "Einspruchsfrist",
            "type_notification" to "Zustellung",
            "type_other" to "Sonstiges",
            "notes_title" to "Private Notizen (Automatisch gespeichert)",
            "academy_title" to "Jura-Akademie",
            "academy_intro" to "Testen Sie Ihr juristisches Wissen, absolvieren Sie Quizfragen und erhalten Sie ein Zertifikat!",
            "academy_start" to "Akademie-Quiz starten",
            "academy_score" to "Aktuelle Punktzahl",
            "academy_cert" to "🏆 Zertifikat für juristische Exzellenz",
            "academy_cert_desc" to "hat die Prüfungen der AL Jura AI OS Akademie mit herausragendem Erfolg bestanden und erhält hiermit dieses Zertifikat.",
            "premium_title" to "Premium-Abonnement",
            "premium_desc" to "Upgrade auf Premium für unbegrenzte Schriftsätze, vollständige Dokumentenanalyse und kontinuierlichen KI-Sprach-Support.",
            "premium_upgrade" to "Auf Premium upgraden",
            "premium_status" to "Mitgliedschaftsstatus",
            "premium_active" to "Premium-Mitglied",
            "premium_free" to "Standard-Mitglied",
            "premium_iban" to "Zahlungs-IBAN (Überweisung)",
            "premium_receipt" to "Beleg hochladen & bestätigen",
            "voice_assistant" to "KI-Sprachanwalt",
            "voice_speak" to "Zum Sprechen gedrückt halten...",
            "camera_scanner" to "Dokumentenkamera (OCR)",
            "camera_capture" to "Scannen & Zusammenfassen",
            "camera_mock_text" to "Mietvertragsentwurf - Vermieter: Ahmet Y., Mieter: Mehmet K. Mietbeginn: 01.01.2026. Miete: 15.000 TRY.",
            "language" to "Sprache / Language",
            "settings" to "Einstellungen",
            "missing_points_title" to "🤖 KI-Lückenanalyse",
            "missing_points_intro" to "Von der KI erkannte Mängel für eine stärkere Verteidigung:",
            "petition_form_title" to "Schriftsatz-Formular",
            "petition_court" to "Zuständiges Gericht (z.B. Arbeitsgericht Istanbul)",
            "petition_plaintiff" to "Kläger-Infos (Name, ID, Adresse)",
            "petition_defendant" to "Beklagten-Infos (Name, Firma, Adresse)",
            "petition_subject" to "Streitgegenstand (z.B. Klage auf Abfindung)",
            "petition_facts" to "Sachverhalt (Erläuterungen)",
            "petition_generate" to "Schriftsatz generieren",
            "petition_export" to "Herunterladen (Simuliert)",
            "active_tab_ofis" to "Kanzlei",
            "active_tab_simulator" to "Fall-Simulator",
            "active_tab_search" to "Recherche",
            "active_tab_petition" to "Studio",
            "active_tab_academy" to "Akademie",
            "active_tab_voice" to "KI-Anwalt",
            "active_tab_camera" to "OCR-Kamera",
            "active_tab_settings" to "Profil & Einstellungen"
        ),
        "AR" to mapOf(
            "app_title" to "نظام محاماة الذكاء الاصطناعي",
            "welcome" to "مرحباً بكم في نظام AL Law للذكاء الاصطناعي",
            "tagline" to "مكتب المحاماة، ومحاكي القضايا، ومحرك البحث، واستوديو العرائض في منصة واحدة قوية.",
            "search_placeholder" to "اكتب سؤالك... (مثال: قانون العمل ساعات العمل الإضافية)",
            "run_search" to "ابحث في محرك القانون",
            "create_file" to "إنشاء ملف قضية جديد",
            "active_files" to "ملفات القضايا النشطة (الحد الأقصى 10)",
            "file_title" to "عنوان القضية / الملف",
            "client_name" to "اسم الموكل",
            "case_description" to "موضوع النزاع وملخص الوقائع",
            "description_hint" to "صِف الواقعة بالتفصيل؛ سيقوم الذكاء الاصطناعي باستخراج التسلسل الزمني والطلبات واقتراحات الأدلة.",
            "save" to "حفظ",
            "cancel" to "إلغاء",
            "status_active" to "نشط",
            "status_closed" to "مغلق",
            "status_pending" to "معلق",
            "workspace" to "مساحة عمل ملف القضية",
            "tab_chat" to "الدماغ القانوني",
            "tab_simulator" to "محاكي القضية",
            "tab_documents" to "مركز المستندات",
            "tab_calendar" to "التقويم والملاحظات",
            "tab_academy" to "الأكاديمية القانونية",
            "tab_petition" to "استوديو العرائض",
            "simulator_run" to "تشغيل محاكي القضية بالذكاء الاصطناعي",
            "simulator_intro" to "تحليل تفاصيل الواقعة لاستخراج التسلسل الزمني والطلبات والنقاط الناقصة وسيناريوهات المخاطر.",
            "simulator_timeline" to "⏰ التسلسل الزمني للأحداث",
            "simulator_claims" to "⚖️ الادعاءات والأدلة",
            "simulator_missing" to "🔍 النقاط الناقصة والعيوب",
            "simulator_scenarios" to "🔮 السيناريوهات القانونية والنتائج",
            "simulator_strengths" to "💪 نقاط القوة والضعف",
            "docs_upload" to "رفع / مسح مستند ضوئياً",
            "docs_name" to "اسم المستند",
            "docs_type" to "نوع المستند",
            "docs_content" to "نص المستند أو ملخصه",
            "docs_unreadable" to "⚠️ تم اكتشاف أجزاء غير مقروءة أو ناقصة!",
            "docs_summary" to "📄 ملخص تحليل المستند",
            "docs_dates" to "📅 التواريخ الهامة",
            "docs_persons" to "👥 الأطراف المذكورة",
            "calendar_add" to "إضافة موعد / حدث هام",
            "calendar_title" to "عنوان الحدث",
            "calendar_type" to "النوع",
            "calendar_date" to "التاريخ (YYYY-MM-DD)",
            "calendar_desc" to "الوصف",
            "type_hearing" to "جلسة محاكمة",
            "type_deadline" to "مهلة الطعن / الاعتراض",
            "type_notification" to "تبليغ رسمي",
            "type_other" to "آخر",
            "notes_title" to "الملاحظات الخاصة (حفظ تلقائي)",
            "academy_title" to "الأكاديمية القانونية",
            "academy_intro" to "اختبر معلوماتك القانونية، واجتاز الاختبارات، واحصل على شهادة التميز!",
            "academy_start" to "بدء اختبار الأكاديمية",
            "academy_score" to "الدرجة الحالية",
            "academy_cert" to "🏆 شهادة التميز القانوني",
            "academy_cert_desc" to "نظير نجاحه المتميز في اختبارات أكاديمية AL Law AI OS، يُمنح هذه الشهادة في الكفاءة القانونية.",
            "premium_title" to "العضوية الممتازة",
            "premium_desc" to "قم بالترقية للحصول على عرائض غير محدودة، وتحليل كامل للوثائق، ودعم مستمر للمحامي الصوتي.",
            "premium_upgrade" to "الترقية للممتاز",
            "premium_status" to "حالة العضوية",
            "premium_active" to "عضو ممتاز",
            "premium_free" to "عضو عادي",
            "premium_iban" to "رقم الحساب الدولي للدفع (IBAN)",
            "premium_receipt" to "رفع الإيصال والتأكيد",
            "voice_assistant" to "المحامي الصوتي الذكي",
            "voice_speak" to "اضغط مع الاستمرار للتحدث...",
            "camera_scanner" to "كاميرا المستندات (OCR)",
            "camera_capture" to "مسح وتلخيص المستند",
            "camera_mock_text" to "مسودة عقد إيجار - المؤجر: أحمد، المستأجر: محمد. تاريخ البدء: 01.01.2026. قيمة الإيجار: 15.000 ليرة.",
            "language" to "اللغة / Language",
            "settings" to "الإعدادات",
            "missing_points_title" to "🤖 تحليل الثغرات والنقاط الناقصة",
            "missing_points_intro" to "الثغرات المكتشفة بواسطة الذكاء الاصطناعي لتقوية موقفك القانوني:",
            "petition_form_title" to "نموذج صياغة العريضة",
            "petition_court" to "المحكمة المختصة (مثال: محكمة العمل الرابعة)",
            "petition_plaintiff" to "بيانات المدعي (الاسم، الهوية، العنوان)",
            "petition_defendant" to "بيانات المدعى عليه (الاسم، العنوان)",
            "petition_subject" to "موضوع الدعوى (مثال: المطالبة بمستحقات نهاية الخدمة)",
            "petition_facts" to "وقائع القضية (شروحات وتفاصيل)",
            "petition_generate" to "صياغة مسودة العريضة",
            "petition_export" to "تحميل بصيغة Word / PDF (محاكاة)",
            "active_tab_ofis" to "مكتب المحاماة",
            "active_tab_simulator" to "محاكي القضية",
            "active_tab_search" to "البحث القانوني",
            "active_tab_petition" to "استوديو العرائض",
            "active_tab_academy" to "الأكاديمية",
            "active_tab_voice" to "المحامي الصوتي",
            "active_tab_camera" to "كاميرا OCR",
            "active_tab_settings" to "الملف الشخصي"
        )
    )

    fun get(key: String, lang: String): String {
        return translations[lang]?.get(key) ?: translations["TR"]?.get(key) ?: key
    }
}
